import { describe, expect, it } from 'vitest';
import { buildEnvContent, backupFileName } from './setup-lib.js';

describe('setup: backup file naming', () => {
  it('produces .env.backup.YYYYMMDDTHHMMSS format', () => {
    const name = backupFileName();
    expect(name).toMatch(/^\.env\.backup\.\d{8}T\d{6}$/);
  });

  it('uses the provided date', () => {
    const name = backupFileName(new Date('2026-02-11T14:30:22.000Z'));
    expect(name).toBe('.env.backup.20260211T143022');
  });
});

describe('setup: .env content generation', () => {
  it('includes required values', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    });
    expect(content).toContain('DISCORD_TOKEN=abc.def.ghi');
    expect(content).toContain('DISCORD_ALLOW_USER_IDS=12345678901234567');
  });

  it('includes core values when provided', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
      DISCORD_GUILD_ID: '98765432109876543',
      CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS: '1',
      CLAUDE_OUTPUT_FORMAT: 'stream-json',
    });
    expect(content).toContain('DISCORD_GUILD_ID=98765432109876543');
    expect(content).toContain('CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS=1');
    expect(content).toContain('CLAUDE_OUTPUT_FORMAT=stream-json');
  });

  it('includes optional values when provided', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
      DISCOCLAW_DISCORD_ACTIONS: '1',
      DISCOCLAW_BEADS_FORUM: '12345678901234567',
    });
    expect(content).toContain('DISCOCLAW_DISCORD_ACTIONS=1');
    expect(content).toContain('DISCOCLAW_BEADS_FORUM=12345678901234567');
  });

  it('omits optional section when no optional values', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    });
    expect(content).not.toContain('# OPTIONAL');
  });

  it('includes reference to .env.example.full', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    });
    expect(content).toContain('.env.example.full');
  });

  it('includes generated-by header and timestamp', () => {
    const ts = new Date('2026-02-11T12:00:00.000Z');
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    }, ts);
    expect(content).toContain('generated by pnpm setup');
    expect(content).toContain('Created: 2026-02-11T12:00:00.000Z');
  });

  it('omits core section when no core values are set', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    });
    expect(content).not.toContain('# CORE');
  });
});

describe('setup: atomic write design', () => {
  it('buildEnvContent produces valid .env syntax (KEY=VALUE per line)', () => {
    const content = buildEnvContent({
      DISCORD_TOKEN: 'abc.def.ghi',
      DISCORD_ALLOW_USER_IDS: '12345678901234567',
    });
    const dataLines = content.split('\n').filter((l) => l && !l.startsWith('#'));
    for (const line of dataLines) {
      expect(line).toMatch(/^[A-Z_]+=.*/);
    }
  });
});
