/**
 * Pure helper functions for the setup wizard.
 * Extracted so tests can import them without triggering the interactive flow.
 */

/** Generate a timestamped backup filename. */
export function backupFileName(now = new Date()): string {
  const ts = now.toISOString().replace(/[-:]/g, '').replace(/\.\d+Z$/, '');
  return `.env.backup.${ts}`;
}

/** Build .env file content from a key-value map. */
export function buildEnvContent(vals: Record<string, string>, now = new Date()): string {
  const lines: string[] = [
    '# Discoclaw — generated by pnpm setup',
    `# Created: ${now.toISOString()}`,
    '',
  ];

  // Required
  lines.push('# REQUIRED');
  lines.push(`DISCORD_TOKEN=${vals.DISCORD_TOKEN ?? ''}`);
  lines.push(`DISCORD_ALLOW_USER_IDS=${vals.DISCORD_ALLOW_USER_IDS ?? ''}`);
  lines.push('');

  // Core
  const coreKeys = ['DISCORD_GUILD_ID', 'CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS', 'CLAUDE_OUTPUT_FORMAT'];
  const hasCore = coreKeys.some((k) => vals[k]);
  if (hasCore) {
    lines.push('# CORE');
    if (vals.DISCORD_GUILD_ID) lines.push(`DISCORD_GUILD_ID=${vals.DISCORD_GUILD_ID}`);
    if (vals.CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS) lines.push(`CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS=${vals.CLAUDE_DANGEROUSLY_SKIP_PERMISSIONS}`);
    if (vals.CLAUDE_OUTPUT_FORMAT) lines.push(`CLAUDE_OUTPUT_FORMAT=${vals.CLAUDE_OUTPUT_FORMAT}`);
    lines.push('');
  }

  // Optional
  const optionalKeys = [
    'DISCOCLAW_DISCORD_ACTIONS',
    'DISCOCLAW_BEADS_FORUM',
    'DISCOCLAW_CRON_FORUM',
    'DISCOCLAW_STATUS_CHANNEL',
  ];
  const hasOptional = optionalKeys.some((k) => vals[k]);
  if (hasOptional) {
    lines.push('# OPTIONAL');
    for (const k of optionalKeys) {
      if (vals[k]) lines.push(`${k}=${vals[k]}`);
    }
    lines.push('');
  }

  lines.push('# For all options, see .env.example.full');
  lines.push('');

  return lines.join('\n');
}
